name: "TruffleHog Secret Scanning - Quick Fix"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    name: TruffleHog Secret Scan
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          # CRITICAL: Do NOT include --no-update, --fail, or --github-actions 
          # These flags are already included by the action and cause duplicate flag errors
          extra_args: --json --results=verified,unknown